AWSTemplateFormatVersion: '2010-09-09'
Description: 'SageMaker Main Stack - Simplified nested stack configuration'

# ========================================
# CloudFormation 専門用語の説明（入門者向け）
# ========================================
# 【Parameters】= 入力値
#   テンプレートを実行する時に指定できる値です。
#   例：スタック名、インスタンスタイプ、リージョンなど
#   この値を変更することで、同じテンプレートから異なる設定の環境を作れます。
#
# 【Resources】= 作成するAWSリソース
#   実際に作成されるAWSのサービスを定義します。
#   例：EC2インスタンス、VPC、IAMロール、SageMakerノートブックなど
#   ここで定義したリソースがAWS上に実際に作成されます。
#
# 【Outputs】= 出力値
#   作成されたリソースの情報を外部に出力します。
#   例：作成されたVPCのID、ノートブックのURL、セキュリティグループのIDなど
#   他のスタックで使用したり、デプロイ後に確認したりできます。
#
# 【Nested Stack】= 入れ子のスタック
#   メインのスタックから他のテンプレートを呼び出す仕組みです。
#   例：VPC用、IAM用、SageMaker用のテンプレートを分けて管理
#   大きなシステムを小さな部品に分けて管理しやすくします。
#
# 【Tags】= タグ
#   AWSリソースに付ける名札のような機能です。
#   例：Environment=production、Project=my-project、Owner=teamA
#   コスト管理や検索、権限管理に使用できます。
#
# 【よく使うCloudFormation構文】
# !Ref          = 他のパラメータやリソースを参照
#                 例：!Ref NotebookInstanceName → パラメータの値を取得
# !GetAtt       = リソースの属性を取得
#                 例：!GetAtt VpcStack.Outputs.VpcId → VPCスタックの出力値を取得
# !Sub          = 文字列の置換
#                 例：!Sub '${ProjectName}-vpc' → ProjectNameの値を埋め込み
# DependsOn     = リソースの作成順序を指定
#                 例：DependsOn: VpcStack → VPCスタックの後に作成

# ========================================
# パラメータセクション（入力値の定義）
# ========================================
# ここで定義した値は、デプロイ時に変更できます
Parameters:
  # SageMaker関連のパラメータ
  NotebookInstanceName:
    Type: String
    Default: 'MySageMakerNotebook'
    Description: 'Name of the SageMaker notebook instance'
    MinLength: 1
    MaxLength: 63
    AllowedPattern: '[a-zA-Z0-9](-*[a-zA-Z0-9])*'
    ConstraintDescription: 'Must contain only alphanumeric characters and hyphens (max 63 characters)'
  
  InstanceType:
    Type: String
    Default: 'ml.t3.medium'
    Description: 'Type of the notebook instance'
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m5.xlarge
      - ml.m5.2xlarge
      - ml.m5.4xlarge
      - ml.p3.2xlarge
      - ml.p3.8xlarge
    ConstraintDescription: 'Please select from available instance types'
  
  # セキュリティ関連のパラメータ
  AllowedIpRange:
    Type: String
    Default: '0.0.0.0/0'
    Description: 'IP address range allowed to access the notebook (CIDR format)'
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: 'Must be a valid CIDR format'
  
  # データ関連のパラメータ
  DefaultS3Bucket:
    Type: String
    Default: ''
    Description: 'Default S3 bucket name (optional)'
  
  VolumeSize:
    Type: Number
    Default: 30
    MinValue: 5
    MaxValue: 16384
    Description: 'EBS volume size (GB)'
  
  # タグ関連のパラメータ
  Environment:
    Type: String
    Default: 'development'
    Description: 'Environment name (development/staging/production)'
    AllowedValues:
      - development
      - staging
      - production
  
  ProjectName:
    Type: String
    Default: 'sagemaker-demo'
    Description: 'Project name'

# ========================================
# リソースセクション（実際に作成するAWSサービス）
# ========================================
# ここで定義したリソースがAWS上に作成されます
Resources:
  # VPC用のネストスタック（常に新規作成）
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cfn-templates.s3.${AWS::Region}.amazonaws.com/sagemaker/templates/vpc-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName      # main-stackパラメータから取得
        Environment: !Ref Environment      # main-stackパラメータから取得
        VpcCidr: '10.0.0.0/16'            # 固定値（初心者向け）
        AvailabilityZone: !Select [0, !GetAZs '']  # 自動的に最初のAZを選択
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: StackType
          Value: 'vpc'
        - Key: Owner
          Value: !Ref AWS::StackName
  
  # IAMロール用のネストスタック
  IamRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cfn-templates.s3.${AWS::Region}.amazonaws.com/sagemaker/templates/iam-role-stack.yaml'
      Parameters:
        ProjectName: !Ref ProjectName      # main-stackパラメータから取得
        Environment: !Ref Environment      # main-stackパラメータから取得
        DefaultS3Bucket: !Ref DefaultS3Bucket  # main-stackパラメータから取得
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-iam-role-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: StackType
          Value: 'iam'
        - Key: Owner
          Value: !Ref AWS::StackName
  
  # セキュリティグループ用のネストスタック
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VpcStack
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cfn-templates.s3.${AWS::Region}.amazonaws.com/sagemaker/templates/security-group-stack.yaml'
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId  # VPCスタックの出力から取得
        AllowedIpRange: !Ref AllowedIpRange  # main-stackパラメータから取得
        ProjectName: !Ref ProjectName      # main-stackパラメータから取得
        Environment: !Ref Environment      # main-stackパラメータから取得
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-security-group-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: StackType
          Value: 'security'
        - Key: Owner
          Value: !Ref AWS::StackName
  
  
  # SageMakerノートブック用のネストスタック
  SageMakerNotebookStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IamRoleStack
      - SecurityGroupStack
    Properties:
      TemplateURL: !Sub 'https://${AWS::AccountId}-cfn-templates.s3.${AWS::Region}.amazonaws.com/sagemaker/templates/sagemaker-notebook-stack.yaml'
      Parameters:
        NotebookInstanceName: !Ref NotebookInstanceName  # main-stackパラメータから取得
        InstanceType: !Ref InstanceType          # main-stackパラメータから取得
        SubnetId: !GetAtt VpcStack.Outputs.PublicSubnetId  # パブリックサブネット（学習・デモ用）
        SecurityGroupId: !GetAtt SecurityGroupStack.Outputs.SecurityGroupId  # SecurityGroupStackの出力から取得
        IamRoleArn: !GetAtt IamRoleStack.Outputs.SageMakerExecutionRoleArn  # IamRoleStackの出力から取得
        VolumeSize: !Ref VolumeSize            # main-stackパラメータから取得
        DefaultS3Bucket: !Ref DefaultS3Bucket      # main-stackパラメータから取得
        ProjectName: !Ref ProjectName          # main-stackパラメータから取得
        Environment: !Ref Environment          # main-stackパラメータから取得
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-sagemaker-notebook-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: NotebookType
          Value: 'primary'
        - Key: StackType
          Value: 'sagemaker'
        - Key: Owner
          Value: !Ref AWS::StackName

  # ========================================
  # 2つ目のノートブック（同じVPC内に追加したい場合）
  # ========================================
  # 以下のコメントアウトを外すと、同じVPC内に2つ目のノートブックが作成されます
  # 
  # SecondSageMakerNotebookStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - IamRoleStack
  #     - SecurityGroupStack
  #     - CustomResourceStack
  #   Properties:
  #     TemplateURL: !Sub 'https://${AWS::AccountId}-cfn-templates.s3.${AWS::Region}.amazonaws.com/sagemaker/templates/sagemaker-notebook-stack.yaml'
  #     Parameters:
  #       NotebookInstanceName: !Sub '${NotebookInstanceName}-second'  # 2つ目のノートブック名
  #       InstanceType: !Ref InstanceType
  #       SubnetId: !GetAtt VpcStack.Outputs.PrivateSubnetId  # 同じVPCのサブネットを使用
  #       SecurityGroupId: !GetAtt SecurityGroupStack.Outputs.SecurityGroupId  # 同じセキュリティグループを使用
  #       IamRoleArn: !GetAtt IamRoleStack.Outputs.SageMakerExecutionRoleArn  # 同じIAMロールを使用
  #       VolumeSize: !Ref VolumeSize
  #       DefaultS3Bucket: !Ref DefaultS3Bucket
  #       CustomResourceServiceToken: !GetAtt CustomResourceStack.Outputs.CustomResourceServiceToken
  #       ProjectName: !Ref ProjectName
  #       Environment: !Ref Environment
  #     Tags:
  #       - Key: Name
  #         Value: !Sub '${ProjectName}-second-sagemaker-notebook-stack'
  #       - Key: Environment
  #         Value: !Ref Environment
  #       - Key: Project
  #         Value: !Ref ProjectName
  #       - Key: NotebookType
  #         Value: 'secondary'
  #       - Key: StackType
  #         Value: 'sagemaker'
  #       - Key: Owner
  #         Value: !Ref AWS::StackName

# ========================================
# 出力セクション（作成されたリソースの情報）
# ========================================
# デプロイ後にこれらの情報を確認できます
Outputs:
  # VPC関連の出力
  VpcId:
    Description: 'VPC ID created by this stack'
    Value: !GetAtt VpcStack.Outputs.VpcId
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
  
  PrivateSubnetId:
    Description: 'Private subnet ID created by this stack'
    Value: !GetAtt VpcStack.Outputs.PrivateSubnetId
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnetId'
  
  # ノートブックインスタンス関連の出力
  NotebookInstanceId:
    Description: 'SageMaker notebook instance ID'
    Value: !GetAtt SageMakerNotebookStack.Outputs.NotebookInstanceId
    Export:
      Name: !Sub '${AWS::StackName}-NotebookInstanceId'
  
  NotebookInstanceName:
    Description: 'SageMaker notebook instance name'
    Value: !GetAtt SageMakerNotebookStack.Outputs.NotebookInstanceName
    Export:
      Name: !Sub '${AWS::StackName}-NotebookInstanceName'
  
  NotebookInstanceUrl:
    Description: 'SageMaker notebook instance URL'
    Value: !GetAtt SageMakerNotebookStack.Outputs.NotebookInstanceUrl
    Export:
      Name: !Sub '${AWS::StackName}-NotebookInstanceUrl'
  
  # IAMロール関連の出力
  SageMakerExecutionRoleArn:
    Description: 'SageMaker execution IAM role ARN'
    Value: !GetAtt IamRoleStack.Outputs.SageMakerExecutionRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-SageMakerExecutionRoleArn'
  
  # セキュリティグループ関連の出力
  SecurityGroupId:
    Description: 'Security group ID for SageMaker notebook'
    Value: !GetAtt SecurityGroupStack.Outputs.SecurityGroupId
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
  
  # 使用ガイド
  QuickStartGuide:
    Description: 'Quick start guide for accessing your notebook'
    Value: !Sub 'Access your notebook at: https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/${NotebookInstanceName}'

  # ========================================
  # 2つ目のノートブック用の出力（コメントアウト）
  # ========================================
  # 2つ目のノートブックを追加した場合は、以下のコメントアウトも外してください
  # 
  # SecondNotebookInstanceId:
  #   Description: 'Second SageMaker notebook instance ID'
  #   Value: !GetAtt SecondSageMakerNotebookStack.Outputs.NotebookInstanceId
  #   Export:
  #     Name: !Sub '${AWS::StackName}-SecondNotebookInstanceId'
  # 
  # SecondNotebookInstanceName:
  #   Description: 'Second SageMaker notebook instance name'
  #   Value: !GetAtt SecondSageMakerNotebookStack.Outputs.NotebookInstanceName
  #   Export:
  #     Name: !Sub '${AWS::StackName}-SecondNotebookInstanceName'
  # 
  # SecondNotebookInstanceUrl:
  #   Description: 'Second SageMaker notebook instance URL'
  #   Value: !GetAtt SecondSageMakerNotebookStack.Outputs.NotebookInstanceUrl
  #   Export:
  #     Name: !Sub '${AWS::StackName}-SecondNotebookInstanceUrl'