AWSTemplateFormatVersion: '2010-09-09'
Description: 'SageMaker Notebook Stack - Simple Version for Testing'

Parameters:
  NotebookInstanceName:
    Type: String
    Description: 'Name of the SageMaker notebook instance'
  
  InstanceType:
    Type: String
    Description: 'Instance type for the notebook'
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: 'Subnet ID for the notebook instance'
  
  SecurityGroupId:
    Type: String
    Description: 'Security group ID for the notebook instance'
  
  IamRoleArn:
    Type: String
    Description: 'IAM role ARN for SageMaker execution'
  
  VolumeSize:
    Type: Number
    Description: 'EBS volume size in GB'
  
  DefaultS3Bucket:
    Type: String
    Default: ''
    Description: 'Default S3 bucket name (optional)'
  
  ProjectName:
    Type: String
    Description: 'Project name'
  
  Environment:
    Type: String
    Description: 'Environment name'

Resources:
  # SageMakerノートブックインスタンス（シンプル版）
  SageMakerNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      NotebookInstanceName: !Ref NotebookInstanceName
      InstanceType: !Ref InstanceType
      RoleArn: !Ref IamRoleArn
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      VolumeSizeInGB: !Ref VolumeSize
      # パブリックサブネット用設定（学習・デモ用）
      DirectInternetAccess: Enabled   # WebUIアクセスのため有効化
      RootAccess: Enabled             # パッケージインストールのため有効化
      
      # ライフサイクル設定（オプション）
      # LifecycleConfigName: !Ref NotebookLifecycleConfig
      
      # タグ設定
      Tags:
        - Key: Name
          Value: !Ref NotebookInstanceName
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # シンプルなライフサイクル設定（オプション）
  # NotebookLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      NotebookInstanceLifecycleConfigName: !Sub '${NotebookInstanceName}-lifecycle'
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -e
              
              # 基本的な環境変数設定
              echo "export PROJECT_NAME=${ProjectName}" >> /home/ec2-user/.bashrc
              echo "export ENVIRONMENT=${Environment}" >> /home/ec2-user/.bashrc
              
              # Gitの基本設定
              sudo -u ec2-user -i <<'EOF'
              git config --global user.name "SageMaker User"
              git config --global user.email "sagemaker@example.com"
              git config --global init.defaultBranch main
              EOF
              
              echo "Basic setup completed!"

Outputs:
  NotebookInstanceId:
    Description: 'SageMaker notebook instance ID'
    Value: !Ref SageMakerNotebookInstance
  
  NotebookInstanceName:
    Description: 'SageMaker notebook instance name'
    Value: !Ref NotebookInstanceName
  
  NotebookInstanceUrl:
    Description: 'SageMaker notebook instance URL'
    Value: !Sub 'https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/${NotebookInstanceName}'